### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by vpavkin** [vpavkin/scala-js-momentjs#22]
Sorry for being annoying, but I have some really active development in progress, that depends on this facade, and a release with all recent fixes would really help.

Since https://github.com/widok/scala-js-momentjs/pull/21 is a breaking change, this should probably be 0.2.0

If there's anything I can do to help with release, just tell :)

**Comment by tindzk** [comment]
Sure, no problem. I have released the latest commit as v0.2.0. Sorry for the inconveniences!

As I am not using this façade anymore and asked @easel to help out with releases etc., would you either of you be interested in taking over the lead?

**Comment by vpavkin** [comment]
@tindzk thank you very much!
Sure, I'm planning to use it quite heavily for observable future, so it would be great if I had this opportunity :)

**Comment by tindzk** [comment]
That's great news.

@easel Is it okay for you if I transfer the ownership to @vpavkin?

**Comment by easel** [comment]
Yeah that's fine with me. Sorry I wasn't able to get the release out before you beat me to it!

**Comment by tindzk** [comment]
Perfect.

@vpavkin Could you please remove (or rename) your fork (`vpavkin/scala-js-momentjs`)? Then I will be able to transfer this repository to your username.

**Comment by vpavkin** [comment]
@tindzk sure, renamed it :)

**Comment by tindzk** [comment]
Strange, now I'm getting:

> vpavkin already has a repository in the widok/scala-js-momentjs network and You can only transfer a repository from an organization to yourself at this time 

It seems that you need to delete your fork.

**Comment by vpavkin** [comment]
deleted :)

**Comment by tindzk** [comment]
Ok, I sent a request.

**Comment by vpavkin** [comment]
transfer complete, thanks!
So last question we need to solve is about namespace for the artifacts.
It's first time I recieve ownership of a repo, that has some releases pubilshed. As far as I understand, the only option I have is to publish to my own namespace from now on. And I will need to republish already published versions as well.

@tindzk, am I correct?

**Comment by easel** [comment]
@vpavkin the github repo doesn't necessarily dictate the sonatype repo. You can create an account on sonatype requesting publishing access to the existing repo and they should take care of it after @tindzk approves it -- I was able to do so although haven't tested my capabilities. Most of that process is documented at http://central.sonatype.org/pages/ossrh-guide.html

**Comment by vpavkin** [comment]
@easel I'm aware of the sonatype publishing process, just didn't know about an option to provide publish access. will take a deeper look, thanks 👍

**Comment by vpavkin** [comment]
created a task, hope it should do the work: https://issues.sonatype.org/browse/OSSRH-14777

**Comment by tindzk** [comment]
You do not need to publish the previous versions. However, I would suggest that you change the organisation everywhere (it was never really related to Widok anyway). You could just use `ru.pavkin`.

**Comment by vpavkin** [comment]
@tindzk ok, I got it. I should get it going on my own from this point. Thanks for your time 👍
