### ISSUE TITLE
Version for scala 2.12.0

### ISSUE THREAD

**Issue by hkirk** [vpavkin/scala-js-momentjs#28]
Is it possible to upgrade for scala 2.12.0?

Best regards

**Comment by vpavkin** [comment]
Hi! Sure, will give it a try in next few hours )

**Comment by vpavkin** [comment]
Published 0.4.1 for 2.11.8 and 2.12.0 to sonatype. Give it a try and, please, let me know if it works correctly :)

**Comment by hkirk** [comment]
Seems to work perfectly. 

Thanks
