### ISSUE TITLE
Compatibility with scalajs-bundler?

### ISSUE THREAD

**Issue by RomanIakovlev** [vpavkin/scala-js-momentjs#31]
I've started to use scalajs-bundler in my project, and all of a sudden this wrapper doesn't work anymore. I get error messages like `Uncaught TypeError: Cannot read property 'utc' of undefined`. Looks like the related javascript file is not loaded. Has anyone tried using this with scalajs-bundler before?

**Comment by vpavkin** [comment]
I haven't. will take a look in folowing days.
Haven't you tried specifying js deps explicitly, does it help in your case?

**Comment by RomanIakovlev** [comment]
What has worked for me is to download the moment.js file and include it manually into my webpage.
