### ISSUE TITLE
Unable to obtain timezone data

### ISSUE THREAD

**Issue by bahuljain** [vpavkin/scala-js-momentjs#32]
A very common use case for this library is obtaining the entire list of time zones along with their corresponding information. Mainly useful in forms where a select field needs to be populated with timezone options. This also requires the moment-timezone-with-data.js file. 

The api call for obtaining the list is ```moment.tz.names()```.

This currently is not supported here.

**Comment by vpavkin** [comment]
hi, @bahuljain!
I'll try to solve this one today

**Comment by vpavkin** [comment]
@bahuljain version 0.8.1 is on sonatype

**Comment by bahuljain** [comment]
@vpavkin thank you so much for the quick response. Cheers
