### ISSUE TITLE
Factory that takes object with unit values

### ISSUE THREAD

**Issue by nafg** [vpavkin/scala-js-momentjs#35]
https://momentjs.com/docs/#/parsing/object/

**Comment by mikla** [comment]
@nafg

You can pass units using js.Dynamic. Like this: 

```scala
Moment(
  js.Dynamic.literal(
	      year = 2019, month = 3, day = 4, minutes = 50, hour = 15, seconds = 59, milliseconds = 999)
)
```

**Comment by nafg** [comment]
Well you can do anything with Dynamic, including not using a facade at all.

If you don't want to implement this in your facade that's your choice of course, but as it stands it isn't as useful as it could be...

**Comment by vpavkin** [comment]
@nafg it's an OSS project and it's your choice as well - just send a PR :)
