### ISSUE TITLE
Bump to scala.js 1.0.0

### ISSUE THREAD

**Issue by aappddeevv** [vpavkin/scala-js-momentjs#43]
Request for a version. If there are no API changes, maybe just use 1.0..0 going forward.

I think 1.0.0 goes final by end of Jan. Right now it's at RC2.

I saw the M8 cross.

**Comment by mikla** [comment]
I will publish support for 1.0.0-RC1 soon.

**Comment by mikla** [comment]
Version `0.10.1` published to sonatype.
